server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:./data/inventory-db;DB_CLOSE_DELAY=-1;AUTO_SERVER=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

app:
  api-key: inventory-secret-key
  products:
    url: http://localhost:8081
    api-key: products-secret-key